"""second  Migration

Revision ID: 4f05011adde7
Revises: c5b3897f3feb
Create Date: 2020-10-30 21:40:50.590858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f05011adde7'
down_revision = 'c5b3897f3feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.drop_constraint('pitches_category_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_category_id_fkey', 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
